# Week 4 Quiz
___


## Question 1

The American Community Survey distributes downloadable data about United States communities. Download the 2006 microdata survey about housing for the state of Idaho using download.file() from here:

https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06hid.csv

and load the data into R. The code book, describing the variable names is here:

https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FPUMSDataDict06.pdf

Apply strsplit() to split all the names of the data frame on the characters "wgtp". What is the value of the 123 element of the resulting list?

In [1]:
if (!file.exists("data/idahohousing.csv")){
    download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06hid.csv",
                 "data/idahohousing.csv")
}
idaho.housing <- read.csv("data/idahohousing.csv")

In [4]:
idaho.names <- names(idaho.housing)

In [8]:
idaho.names.split <- strsplit(idaho.names, "wgtp")

In [9]:
idaho.names.split[[123]]

[1] ""   "15"

In [10]:
idaho.names[[123]]

[1] "wgtp15"

## Question 2
Load the Gross Domestic Product data for the 190 ranked countries in this data set:

https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv

Remove the commas from the GDP numbers in millions of dollars and average them. What is the average?

Original data sources:

http://data.worldbank.org/data-catalog/GDP-ranking-table

In [11]:
if (!file.exists("data/GDP.csv")) {
    download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv", "data/GDP.csv")
}

In [13]:
readLines("data/GDP.csv", n=10)

[1] ",Gross domestic product 2012,,,,,,,,"      
 [2] ",,,,,,,,,"                                 
 [3] ",,,,(millions of,,,,,"                     
 [4] ",Ranking,,Economy,US dollars),,,,,"        
 [5] ",,,,,,,,,"                                 
 [6] "USA,1,,United States,\" 16,244,600 \",,,,,"
 [7] "CHN,2,,China,\" 8,227,103 \",,,,,"         
 [8] "JPN,3,,Japan,\" 5,959,718 \",,,,,"         
 [9] "DEU,4,,Germany,\" 3,428,131 \",,,,,"       
[10] "FRA,5,,France,\" 2,612,878 \",,,,,"

In [22]:
gdp <- read.csv("data/GDP.csv", skip=5, header = FALSE)

In [23]:
names(gdp)

[1] "V1"  "V2"  "V3"  "V4"  "V5"  "V6"  "V7"  "V8"  "V9"  "V10"

In [24]:
tail(gdp)

V1 V2 V3 V4 V5 V6 V7 V8 V9 V10
321       NA          NA NA NA NA 
322       NA          NA NA NA NA 
323       NA          NA NA NA NA 
324       NA          NA NA NA NA 
325       NA          NA NA NA NA 
326       NA          NA NA NA NA

In [25]:
gdp <- gdp[1:190,]

In [26]:
tail(gdp)

Warning message in FUN(X[[i]], ...):
“input string 4 is invalid in this locale”Warning message in FUN(X[[i]], ...):
“input string 4 is invalid in this locale”Warning message in FUN(X[[i]], ...):
“input string 4 is invalid in this locale”Warning message in FUN(X[[i]], ...):
“input string 4 is invalid in this locale”Warning message in FUN(X[[i]], ...):
“input string 4 is invalid in this locale”Warning message in FUN(X[[i]], ...):
“input string 4 is invalid in this locale”Warning message in FUN(X[[i]], ...):
“input string 4 is invalid in this locale”Warning message in FUN(X[[i]], ...):
“input string 4 is invalid in this locale”Warning message in FUN(X[[i]], ...):
“input string 4 is invalid in this locale”Warning message in FUN(X[[i]], ...):
“input string 4 is invalid in this locale”Warning message in FUN(X[[i]], ...):
“input string 4 is invalid in this locale”Warning message in FUN(X[[i]], ...):
“input string 4 is invalid in this locale”Warning message in FUN(X[[i]], ...):
“input string 4

V1  V2  V3 V4                          V5    V6 V7 V8 V9 V10
185 FSM 185 NA Micronesia, Fed. Sts.        326     NA NA NA NA 
186 STP 186 NA S\xe3o Tom\xe9 and Principe  263     NA NA NA NA 
187 PLW 187 NA Palau                        228     NA NA NA NA 
188 MHL 188 NA Marshall Islands             182     NA NA NA NA 
189 KIR 189 NA Kiribati                     175     NA NA NA NA 
190 TUV 190 NA Tuvalu                       40      NA NA NA NA

In [29]:
gdp$V5 <- gsub(",", "", gdp$V5)

In [31]:
gdp$V5 <- as.numeric(gdp$V5)

In [32]:
mean(gdp$V5)

[1] 377652.4

## Question 3
In the data set from Question 2 what is a regular expression that would allow you to count the number of countries whose name begins with "United"? Assume that the variable with the country names in it is named countryNames. How many countries begin with United?

In [33]:
grep("^United", gdp$V4)

Warning message in grep("^United", gdp$V4):
“input string 99 is invalid in this locale”Warning message in grep("^United", gdp$V4):
“input string 186 is invalid in this locale”

[1]  1  6 32

Out of curiousity, what's the error about strings 99 and 186 about?

In [36]:
gdp$V4[99]

[1] C\xf4te d'Ivoire
229 Levels:    East Asia & Pacific   Euro area ... Zimbabwe

In [37]:
gdp$V4[186]

[1] S\xe3o Tom\xe9 and Principe
229 Levels:    East Asia & Pacific   Euro area ... Zimbabwe

Accent marks! Typical.

## Question 4

Load the Gross Domestic Product data for the 190 ranked countries in this data set:

https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv

Load the educational data from this data set:

https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FEDSTATS_Country.csv

Match the data based on the country shortcode. Of the countries for which the end of the fiscal year is available, how many end in June?

Original data sources:

http://data.worldbank.org/data-catalog/GDP-ranking-table

http://data.worldbank.org/data-catalog/ed-stats

In [39]:
if (!file.exists("data/GDP.csv")) {
    download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv", "data/GDP.csv")
}

In [41]:
gdp <- read.csv("data/GDP.csv", skip=5, header = FALSE)
gdp <- gdp[1:190,]

In [44]:
if (!file.exists("data/FEDSTATS.csv")) {
    download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FEDSTATS_Country.csv", "data/FEDSTATS.csv")
}

In [52]:
fedstats <- read.csv("data/FEDSTATS.csv")
str(fedstats)

'data.frame':	234 obs. of  31 variables:
 $ CountryCode                                      : Factor w/ 234 levels "ABW","ADO","AFG",..: 1 2 3 4 5 6 7 8 9 10 ...
 $ Long.Name                                        : Factor w/ 234 levels "American Samoa",..: 5 104 57 99 109 226 4 110 1 2 ...
 $ Income.Group                                     : Factor w/ 6 levels "","High income: nonOECD",..: 2 2 4 5 6 2 6 5 6 6 ...
 $ Region                                           : Factor w/ 8 levels "","East Asia & Pacific",..: 4 3 7 8 3 5 4 3 2 4 ...
 $ Lending.category                                 : Factor w/ 4 levels "","Blend","IBRD",..: 1 1 4 4 3 1 3 2 1 3 ...
 $ Other.groups                                     : Factor w/ 3 levels "","Euro area",..: 1 1 3 1 1 1 1 1 1 1 ...
 $ Currency.Unit                                    : Factor w/ 155 levels "","Afghan afghani",..: 8 49 2 5 3 144 6 7 145 44 ...
 $ Latest.population.census                         : Factor w/ 28 levels "","1970","1979"

In [47]:
merged <- merge(gdp, fedstats, by.x = "V1", by.y = "CountryCode")

In [49]:
str(merged)

'data.frame':	189 obs. of  40 variables:
 $ V1                                               : Factor w/ 229 levels "","ABW","ADO",..: 2 4 5 6 7 8 9 11 12 13 ...
 $ V2                                               : Factor w/ 194 levels "",".. Not available.  ",..: 72 10 149 32 118 111 41 84 26 112 ...
 $ V3                                               : logi  NA NA NA NA NA NA ...
 $ V4                                               : Factor w/ 229 levels "","  East Asia & Pacific",..: 20 11 16 12 216 18 19 17 21 22 ...
 $ V5                                               : Factor w/ 205 levels ""," 1,008 "," 1,129 ",..: 65 68 24 26 109 134 186 5 11 118 ...
 $ V6                                               : Factor w/ 7 levels "","a","b","c",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ V7                                               : logi  NA NA NA NA NA NA ...
 $ V8                                               : logi  NA NA NA NA NA NA ...
 $ V9                                               : 

In [50]:
names(merged)

[1] "V1"                                               
 [2] "V2"                                               
 [3] "V3"                                               
 [4] "V4"                                               
 [5] "V5"                                               
 [6] "V6"                                               
 [7] "V7"                                               
 [8] "V8"                                               
 [9] "V9"                                               
[10] "V10"                                              
[11] "Long.Name"                                        
[12] "Income.Group"                                     
[13] "Region"                                           
[14] "Lending.category"                                 
[15] "Other.groups"                                     
[16] "Currency.Unit"                                    
[17] "Latest.population.census"                         
[18] "Latest.household.survey"                          
[19] "Special.Notes"                                    
[20] "National.accounts.base.year"                      
[21] "National.accounts.reference.year"                 
[22] "System.of.National.Accounts"                      
[23] "SNA.price.valuation"                              
[24] "Alternative.conversion.factor"                    
[25] "PPP.survey.year"                                  
[26] "Balance.of.Payments.Manual.in.use"                
[27] "External.debt.Reporting.status"                   
[28] "System.of.trade"                                  
[29] "Government.Accounting.concept"                    
[30] "IMF.data.dissemination.standard"                  
[31] "Source.of.most.recent.Income.and.expenditure.data"
[32] "Vital.registration.complete"                      
[33] "Latest.agricultural.census"                       
[34] "Latest.industrial.data"                           
[35] "Latest.trade.data"                                
[36] "Latest.water.withdrawal.data"                     
[37] "X2.alpha.code"                                    
[38] "WB.2.code"                                        
[39] "Table.Name"                                       
[40] "Short.Name"

In [56]:
table(grepl("^Fiscal year end: June", merged$Special.Notes))


FALSE  TRUE 
  176    13 

You can use the quantmod (http://www.quantmod.com/) package to get historical stock prices for publicly traded companies on the NASDAQ and NYSE. Use the following code to download data on Amazon's stock price and get the times the data was sampled.

```
library(quantmod)
amzn = getSymbols("AMZN",auto.assign=FALSE)
sampleTimes = index(amzn)
```
How many values were collected in 2012? How many values were collected on Mondays in 2012?

In [59]:
install.packages("quantmod")

also installing the dependencies ‘xts’, ‘TTR’

Updating HTML index of packages in '.Library'
Making 'packages.html' ... done


In [69]:
library(lubridate)


Attaching package: ‘lubridate’

The following object is masked from ‘package:base’:

    date



In [60]:
library(quantmod)

Loading required package: xts
Loading required package: zoo

Attaching package: ‘zoo’

The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric

Loading required package: TTR
Version 0.4-0 included new data defaults. See ?getSymbols.


In [61]:
amzn <- getSymbols("AMZN", auto.assign=FALSE)

‘getSymbols’ currently uses auto.assign=TRUE by default, but will
use auto.assign=FALSE in 0.5-0. You will still be able to use
‘loadSymbols’ to automatically load data. getOption("getSymbols.env")
and getOption("getSymbols.auto.assign") will still be checked for
alternate defaults.

This message is shown once per session and may be disabled by setting 
options("getSymbols.warning4.0"=FALSE). See ?getSymbols for details.

Please see the Warning section of ‘?getSymbols.yahoo’ for details.

This message is shown once per session and may be disabled by setting
options("getSymbols.yahoo.warning"=FALSE).


In [62]:
sampleTimes <- index(amzn)

In [63]:
str(sampleTimes)

 Date[1:2828], format: "2007-01-03" "2007-01-04" "2007-01-05" "2007-01-08" ...


In [85]:
str(sampleTimes)

 Date[1:2828], format: "2007-01-03" "2007-01-04" "2007-01-05" "2007-01-08" ...


In [86]:
table(format(sampleTimes, "%Y") == 2012)


FALSE  TRUE 
 2578   250 

In [87]:
table(format(sampleTimes, "%a%Y") == "Mon2012")


FALSE  TRUE 
 2781    47 